# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-15 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcontent', models.CharField(max_length=500)),
                ('ptitle', models.IntegerField(max_length=50)),
                ('rid', models.IntegerField(default=0)),
                ('ptime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'blog_posts',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password_hash', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'blog_user',
            },
        ),
        migrations.AddField(
            model_name='posts',
            name='puser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.User'),
        ),
    ]
