# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-15 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='ptitle',
            field=models.CharField(max_length=50),
        ),
    ]
