# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-16 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20171215_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='ptitle',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
