# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-27 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20171226_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='pcollect_user',
            field=models.ManyToManyField(related_name='cuser', to='App.User'),
        ),
    ]
